/**
 * LandingPage Component - REDESIGNED
 * 
 * Modern, classy landing page inspired by Vercel, Linear, and Stripe.
 * Features:
 * - Premium hero section with animated gradient
 * - Real-time animated statistics
 * - Feature cards with glassmorphism
 * - Smooth scroll animations
 * - Professional CTAs with hover effects
 * - Social proof section
 * - Modern color palette and typography
 */

import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion, useScroll, useTransform } from 'framer-motion';
import {
  Sparkles, Code, Brain, Trophy, Zap, Target,
  ArrowRight, CheckCircle2, Users, BookOpen, Rocket,
  TrendingUp, Star, Award
} from 'lucide-react';

export default function LandingPage() {
  const navigate = useNavigate();
  const { scrollYProgress } = useScroll();
  const opacity = useTransform(scrollYProgress, [0, 0.2], [1, 0]);

  // Animated statistics
  const [stats, setStats] = useState({
    topics: 0,
    users: 0,
    challenges: 0,
    success: 0,
  });

  useEffect(() => {
    // Animate numbers on mount
    const targetStats = { topics: 500, users: 1200, challenges: 2500, success: 94 };
    const duration = 2000; // 2 seconds
    const steps = 60;
    const interval = duration / steps;

    let step = 0;
    const timer = setInterval(() => {
      step++;
      const progress = step / steps;

      setStats({
        topics: Math.floor(targetStats.topics * progress),
        users: Math.floor(targetStats.users * progress),
        challenges: Math.floor(targetStats.challenges * progress),
        success: Math.floor(targetStats.success * progress),
      });

      if (step >= steps) {
        clearInterval(timer);
        setStats(targetStats);
      }
    }, interval);

    return () => clearInterval(timer);
  }, []);

  const features = [
    {
      icon: Brain,
      title: 'AI-Powered Learning',
      description: 'Personalized roadmaps generated by Gemini AI, tailored to your skill level and goals.',
      gradient: 'from-violet-500 to-purple-600',
    },
    {
      icon: Code,
      title: 'Interactive Coding',
      description: 'Practice with real-world challenges in our embedded IDE with instant feedback.',
      gradient: 'from-blue-500 to-cyan-600',
    },
    {
      icon: Trophy,
      title: 'Gamified Progress',
      description: 'Track streaks, earn badges, and level up as you master new skills.',
      gradient: 'from-orange-500 to-red-600',
    },
    {
      icon: Zap,
      title: 'Lightning Fast',
      description: 'Optimized performance with smart caching for instant content delivery.',
      gradient: 'from-yellow-500 to-orange-600',
    },
    {
      icon: Target,
      title: 'Career-Focused',
      description: '16+ career paths from Full Stack to AI/ML, all with structured roadmaps.',
      gradient: 'from-green-500 to-emerald-600',
    },
    {
      icon: Users,
      title: 'Community Driven',
      description: 'Join thousands of learners on their journey to tech mastery.',
      gradient: 'from-pink-500 to-rose-600',
    },
  ];

  const careerPaths = [
    { name: 'Full Stack', icon: '💻', popular: true },
    { name: 'AI/ML', icon: '🤖', popular: true },
    { name: 'DevOps', icon: '🔧', popular: false },
    { name: 'Blockchain', icon: '⛓️', popular: false },
    { name: 'Mobile', icon: '📱', popular: true },
    { name: 'Data Science', icon: '📊', popular: true },
  ];

  return (
    <div className="min-h-screen bg-gradient-to-b from-gray-50 to-white">
      {/* Hero Section */}
      <motion.section
        style={{ opacity }}
        className="relative py-20 md:py-32 overflow-hidden"
      >
        {/* Animated Background Gradient */}
        <div className="absolute inset-0 bg-gradient-to-br from-indigo-50 via-purple-50 to-pink-50 opacity-60"></div>
        <div className="absolute inset-0 bg-grid-pattern opacity-5"></div>

        <div className="container mx-auto px-4 relative z-10">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className="text-center max-w-5xl mx-auto"
          >
            {/* Badge */}
            <motion.div
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ delay: 0.2 }}
              className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white/80 backdrop-blur-sm shadow-lg border border-gray-200 mb-6"
            >
              <Sparkles className="w-4 h-4 text-indigo-600" />
              <span className="text-sm font-medium text-gray-700">AI-Powered Learning Platform</span>
              <Star className="w-4 h-4 text-yellow-500 fill-yellow-500" />
            </motion.div>

            {/* Main Heading */}
            <motion.h1
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.3 }}
              className="text-5xl md:text-7xl font-bold mb-6 leading-tight"
            >
              <span className="bg-gradient-to-r from-indigo-600 via-purple-600 to-pink-600 bg-clip-text text-transparent">
                Master Tech Skills
              </span>
              <br />
              <span className="text-gray-900">With AI Guidance</span>
            </motion.h1>

            {/* Subtitle */}
            <motion.p
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.5 }}
              className="text-xl md:text-2xl text-gray-600 mb-10 max-w-3xl mx-auto leading-relaxed"
            >
              Transform your career with personalized roadmaps, interactive coding challenges, and AI-powered assessments.
              <span className="font-semibold text-gray-900"> Learn smarter, not harder.</span>
            </motion.p>

            {/* CTA Buttons */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.7 }}
              className="flex flex-col sm:flex-row gap-4 justify-center items-center"
            >
              <button
                onClick={() => navigate('/roadmap')}
                className="group relative px-8 py-4 bg-gradient-to-r from-indigo-600 to-purple-600 text-white font-semibold rounded-xl shadow-lg hover:shadow-xl transform hover:-translate-y-0.5 transition-all duration-200 flex items-center gap-2"
              >
                Start Learning Free
                <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
              </button>

              <button
                onClick={() => navigate('/search')}
                className="px-8 py-4 bg-white text-gray-900 font-semibold rounded-xl shadow-md hover:shadow-lg border border-gray-200 transform hover:-translate-y-0.5 transition-all duration-200"
              >
                Explore Topics
              </button>
            </motion.div>

            {/* Stats Bar */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.9 }}
              className="mt-16 grid grid-cols-2 md:grid-cols-4 gap-8 max-w-4xl mx-auto"
            >
              <div className="text-center">
                <div className="text-4xl font-bold bg-gradient-to-r from-indigo-600 to-purple-600 bg-clip-text text-transparent">
                  {stats.topics}+
                </div>
                <div className="text-sm text-gray-600 mt-1">Learning Topics</div>
              </div>
              <div className="text-center">
                <div className="text-4xl font-bold bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent">
                  {stats.users}+
                </div>
                <div className="text-sm text-gray-600 mt-1">Active Learners</div>
              </div>
              <div className="text-center">
                <div className="text-4xl font-bold bg-gradient-to-r from-blue-600 to-cyan-600 bg-clip-text text-transparent">
                  {stats.challenges}+
                </div>
                <div className="text-sm text-gray-600 mt-1">Coding Challenges</div>
              </div>
              <div className="text-center">
                <div className="text-4xl font-bold bg-gradient-to-r from-green-600 to-emerald-600 bg-clip-text text-transparent">
                  {stats.success}%
                </div>
                <div className="text-sm text-gray-600 mt-1">Success Rate</div>
              </div>
            </motion.div>
          </motion.div>
        </div>
      </motion.section>

      {/* Career Paths Section */}
      <section className="py-20 bg-white">
        <div className="container mx-auto px-4">
          <div className="text-center mb-12">
            <h2 className="text-4xl font-bold mb-4">Choose Your Career Path</h2>
            <p className="text-xl text-gray-600">16+ structured roadmaps designed for real-world success</p>
          </div>

          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4 max-w-5xl mx-auto">
            {careerPaths.map((path, index) => (
              <motion.div
                key={path.name}
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ delay: index * 0.1 }}
                whileHover={{ scale: 1.05 }}
                onClick={() => navigate('/roadmap')}
                className="relative cursor-pointer p-6 bg-gradient-to-br from-white to-gray-50 rounded-2xl shadow-md hover:shadow-xl border border-gray-200 transition-all duration-300"
              >
                {path.popular && (
                  <div className="absolute -top-2 -right-2 px-2 py-1 bg-gradient-to-r from-orange-500 to-red-500 text-white text-xs font-bold rounded-full">
                    HOT
                  </div>
                )}
                <div className="text-4xl mb-2">{path.icon}</div>
                <div className="text-sm font-semibold text-gray-900">{path.name}</div>
              </motion.div>
            ))}
          </div>

          <div className="text-center mt-8">
            <button
              onClick={() => navigate('/roadmap')}
              className="text-indigo-600 font-semibold hover:text-indigo-700 flex items-center gap-2 mx-auto"
            >
              View all 16 paths
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 bg-gradient-to-b from-gray-50 to-white">
        <div className="container mx-auto px-4">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold mb-4">Everything You Need to Succeed</h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Built with modern technology and best practices for an exceptional learning experience
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 max-w-6xl mx-auto">
            {features.map((feature, index) => (
              <motion.div
                key={feature.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.1 }}
                className="group p-8 bg-white rounded-2xl shadow-md hover:shadow-2xl border border-gray-100 transition-all duration-300"
              >
                <div className={`inline-flex p-4 rounded-xl bg-gradient-to-r ${feature.gradient} mb-4 group-hover:scale-110 transition-transform`}>
                  <feature.icon className="w-6 h-6 text-white" />
                </div>
                <h3 className="text-xl font-bold mb-3 text-gray-900">{feature.title}</h3>
                <p className="text-gray-600 leading-relaxed">{feature.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Social Proof & CTA Section */}
      <section className="py-20 bg-gradient-to-r from-indigo-600 via-purple-600 to-pink-600 text-white">
        <div className="container mx-auto px-4 text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="max-w-4xl mx-auto"
          >
            <Award className="w-16 h-16 mx-auto mb-6" />
            <h2 className="text-4xl md:text-5xl font-bold mb-6">
              Ready to Transform Your Career?
            </h2>
            <p className="text-xl mb-8 text-white/90">
              Join thousands of learners who are mastering tech skills with AI-powered guidance
            </p>

            <div className="flex flex-col sm:flex-row gap-4 justify-center mb-12">
              <button
                onClick={() => navigate('/signup')}
                className="px-8 py-4 bg-white text-indigo-600 font-bold rounded-xl shadow-lg hover:shadow-xl transform hover:-translate-y-0.5 transition-all duration-200"
              >
                Sign Up Free
              </button>
              <button
                onClick={() => navigate('/roadmap')}
                className="px-8 py-4 bg-white/10 backdrop-blur-sm text-white font-bold rounded-xl border-2 border-white/30 hover:bg-white/20 transition-all duration-200"
              >
                Browse Roadmaps
              </button>
            </div>

            {/* Trust Indicators */}
            <div className="flex flex-wrap justify-center items-center gap-8 text-sm text-white/80">
              <div className="flex items-center gap-2">
                <CheckCircle2 className="w-5 h-5" />
                <span>100% Free Forever</span>
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle2 className="w-5 h-5" />
                <span>No Credit Card Required</span>
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle2 className="w-5 h-5" />
                <span>AI-Powered Content</span>
              </div>
            </div>
          </motion.div>
        </div>
      </section>
    </div>
  );
}
